/* Generated By:JavaCC: Do not edit this line. CParserConstants.java */
package org.codecover.instrumentation.c.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 1;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 2;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 3;
  /** RegularExpression Id. */
  int HEX_LITERAL = 4;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 5;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 6;
  /** RegularExpression Id. */
  int EXPONENT = 7;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 8;
  /** RegularExpression Id. */
  int STRING_LITERAL = 9;
  /** RegularExpression Id. */
  int CONTINUE = 10;
  /** RegularExpression Id. */
  int VOLATILE = 11;
  /** RegularExpression Id. */
  int REGISTER = 12;
  /** RegularExpression Id. */
  int UNSIGNED = 13;
  /** RegularExpression Id. */
  int TYPEDEF = 14;
  /** RegularExpression Id. */
  int DFLT = 15;
  /** RegularExpression Id. */
  int DOUBLE = 16;
  /** RegularExpression Id. */
  int SIZEOF = 17;
  /** RegularExpression Id. */
  int SWITCH = 18;
  /** RegularExpression Id. */
  int RETURN = 19;
  /** RegularExpression Id. */
  int EXTERN = 20;
  /** RegularExpression Id. */
  int STRUCT = 21;
  /** RegularExpression Id. */
  int STATIC = 22;
  /** RegularExpression Id. */
  int SIGNED = 23;
  /** RegularExpression Id. */
  int WHILE = 24;
  /** RegularExpression Id. */
  int BREAK = 25;
  /** RegularExpression Id. */
  int UNION = 26;
  /** RegularExpression Id. */
  int CONST = 27;
  /** RegularExpression Id. */
  int FLOAT = 28;
  /** RegularExpression Id. */
  int SHORT = 29;
  /** RegularExpression Id. */
  int ELSE = 30;
  /** RegularExpression Id. */
  int CASE = 31;
  /** RegularExpression Id. */
  int LONG = 32;
  /** RegularExpression Id. */
  int ENUM = 33;
  /** RegularExpression Id. */
  int AUTO = 34;
  /** RegularExpression Id. */
  int VOID = 35;
  /** RegularExpression Id. */
  int CHAR = 36;
  /** RegularExpression Id. */
  int GOTO = 37;
  /** RegularExpression Id. */
  int FOR = 38;
  /** RegularExpression Id. */
  int INT = 39;
  /** RegularExpression Id. */
  int IF = 40;
  /** RegularExpression Id. */
  int DO = 41;
  /** RegularExpression Id. */
  int IDENTIFIER = 42;
  /** RegularExpression Id. */
  int LETTER = 43;
  /** RegularExpression Id. */
  int DIGIT = 44;
  /** RegularExpression Id. */
  int INC = 45;
  /** RegularExpression Id. */
  int DEC = 46;
  /** RegularExpression Id. */
  int LAND = 47;
  /** RegularExpression Id. */
  int LOR = 48;
  /** RegularExpression Id. */
  int RBL = 49;
  /** RegularExpression Id. */
  int RBR = 50;
  /** RegularExpression Id. */
  int CBL = 51;
  /** RegularExpression Id. */
  int CBR = 52;
  /** RegularExpression Id. */
  int SBL = 53;
  /** RegularExpression Id. */
  int SBR = 54;
  /** RegularExpression Id. */
  int STAR = 55;
  /** RegularExpression Id. */
  int SLASH = 56;
  /** RegularExpression Id. */
  int MOD = 57;
  /** RegularExpression Id. */
  int PLUS = 58;
  /** RegularExpression Id. */
  int MINUS = 59;
  /** RegularExpression Id. */
  int EXCL = 60;
  /** RegularExpression Id. */
  int AMP = 61;
  /** RegularExpression Id. */
  int QEM = 62;
  /** RegularExpression Id. */
  int TILDE = 63;
  /** RegularExpression Id. */
  int CARE = 64;
  /** RegularExpression Id. */
  int PIPE = 65;
  /** RegularExpression Id. */
  int COMMA = 66;
  /** RegularExpression Id. */
  int SEMICOLON = 67;
  /** RegularExpression Id. */
  int COLON = 68;
  /** RegularExpression Id. */
  int ASSIGNMENT = 69;
  /** RegularExpression Id. */
  int DOT = 70;
  /** RegularExpression Id. */
  int LESS = 71;
  /** RegularExpression Id. */
  int GREATER = 72;
  /** RegularExpression Id. */
  int ELLIPSIS = 73;
  /** RegularExpression Id. */
  int MULT_EQ = 74;
  /** RegularExpression Id. */
  int DIV_EQ = 75;
  /** RegularExpression Id. */
  int MOD_EQ = 76;
  /** RegularExpression Id. */
  int PLUS_EQ = 77;
  /** RegularExpression Id. */
  int SUB_EQ = 78;
  /** RegularExpression Id. */
  int LSH_EQ = 79;
  /** RegularExpression Id. */
  int RSH_EQ = 80;
  /** RegularExpression Id. */
  int AND_EQ = 81;
  /** RegularExpression Id. */
  int XOR_EQ = 82;
  /** RegularExpression Id. */
  int OR_EQ = 83;
  /** RegularExpression Id. */
  int EQ = 84;
  /** RegularExpression Id. */
  int NE = 85;
  /** RegularExpression Id. */
  int LE = 86;
  /** RegularExpression Id. */
  int GE = 87;
  /** RegularExpression Id. */
  int LSH = 88;
  /** RegularExpression Id. */
  int RSH = 89;
  /** RegularExpression Id. */
  int ARROW = 90;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NUMBER>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"continue\"",
    "\"volatile\"",
    "\"register\"",
    "\"unsigned\"",
    "\"typedef\"",
    "\"default\"",
    "\"double\"",
    "\"sizeof\"",
    "\"switch\"",
    "\"return\"",
    "\"extern\"",
    "\"struct\"",
    "\"static\"",
    "\"signed\"",
    "\"while\"",
    "\"break\"",
    "\"union\"",
    "\"const\"",
    "\"float\"",
    "\"short\"",
    "\"else\"",
    "\"case\"",
    "\"long\"",
    "\"enum\"",
    "\"auto\"",
    "\"void\"",
    "\"char\"",
    "\"goto\"",
    "\"for\"",
    "\"int\"",
    "\"if\"",
    "\"do\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"++\"",
    "\"--\"",
    "\"&&\"",
    "\"||\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"+\"",
    "\"-\"",
    "\"!\"",
    "\"&\"",
    "\"?\"",
    "\"~\"",
    "\"^\"",
    "\"|\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"=\"",
    "\".\"",
    "\"<\"",
    "\">\"",
    "\"...\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"+=\"",
    "\"-=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&=\"",
    "\"^=\"",
    "\"|=\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\"->\"",
  };

}
