//
// Generated by JTB 1.3.2
//

package org.codecover.instrumentation.c.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> "{"
 * nodeOptional -> [ DeclarationList() ]
 * nodeOptional1 -> [ StatementList() ]
 * nodeToken1 -> "}"
 * </PRE>
 */
public class CompoundStatement extends org.codecover.instrumentation.c.adapter.CCNode implements Node {
   public NodeToken nodeToken;
   public NodeOptional nodeOptional;
   public NodeOptional nodeOptional1;
   public NodeToken nodeToken1;

   public CompoundStatement(NodeToken n0, NodeOptional n1, NodeOptional n2, NodeToken n3) {
      nodeToken = n0;
      nodeOptional = n1;
      nodeOptional1 = n2;
      nodeToken1 = n3;
   }

   public CompoundStatement(NodeOptional n0, NodeOptional n1) {
      nodeToken = new NodeToken("{");
      nodeOptional = n0;
      nodeOptional1 = n1;
      nodeToken1 = new NodeToken("}");
   }

   public void accept(org.codecover.instrumentation.c.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(org.codecover.instrumentation.c.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(org.codecover.instrumentation.c.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(org.codecover.instrumentation.c.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

