//
// Generated by JTB 1.3.2
//

package org.codecover.instrumentation.c.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeOptional -> [ Pointer() ]
 * directDeclarator -> DirectDeclarator()
 * </PRE>
 */
public class Declarator extends org.codecover.instrumentation.c.adapter.CCNode implements Node {
   public NodeOptional nodeOptional;
   public DirectDeclarator directDeclarator;

   public Declarator(NodeOptional n0, DirectDeclarator n1) {
      nodeOptional = n0;
      directDeclarator = n1;
   }

   public void accept(org.codecover.instrumentation.c.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(org.codecover.instrumentation.c.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(org.codecover.instrumentation.c.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(org.codecover.instrumentation.c.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

