//
// Generated by JTB 1.3.2
//

package org.codecover.instrumentation.c.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> &lt;ENUM&gt;
 * nodeChoice -> ( [ &lt;IDENTIFIER&gt; ] "{" EnumeratorList() "}" | &lt;IDENTIFIER&gt; )
 * </PRE>
 */
public class EnumSpecifier extends org.codecover.instrumentation.c.adapter.CCNode implements Node {
   public NodeToken nodeToken;
   public NodeChoice nodeChoice;

   public EnumSpecifier(NodeToken n0, NodeChoice n1) {
      nodeToken = n0;
      nodeChoice = n1;
   }

   public EnumSpecifier(NodeChoice n0) {
      nodeToken = new NodeToken("enum");
      nodeChoice = n0;
   }

   public void accept(org.codecover.instrumentation.c.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(org.codecover.instrumentation.c.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(org.codecover.instrumentation.c.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(org.codecover.instrumentation.c.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

