//
// Generated by JTB 1.3.2
//

package org.codecover.instrumentation.c.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeOptional -> [ DeclarationSpecifiers() ]
 * declarator -> Declarator()
 * nodeOptional1 -> [ DeclarationList() ]
 * compoundStatement -> CompoundStatement()
 * </PRE>
 */
public class FunctionDefinition extends org.codecover.instrumentation.c.adapter.CCNode implements Node {
   public NodeOptional nodeOptional;
   public Declarator declarator;
   public NodeOptional nodeOptional1;
   public CompoundStatement compoundStatement;

   public FunctionDefinition(NodeOptional n0, Declarator n1, NodeOptional n2, CompoundStatement n3) {
      nodeOptional = n0;
      declarator = n1;
      nodeOptional1 = n2;
      compoundStatement = n3;
   }

   public void accept(org.codecover.instrumentation.c.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(org.codecover.instrumentation.c.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(org.codecover.instrumentation.c.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(org.codecover.instrumentation.c.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

