//
// Generated by JTB 1.3.2
//

package org.codecover.instrumentation.c.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * exclusiveORExpression -> ExclusiveORExpression()
 * nodeOptional -> [ "|" InclusiveORExpression() ]
 * </PRE>
 */
public class InclusiveORExpression extends org.codecover.instrumentation.c.adapter.CCNode implements Node {
   public ExclusiveORExpression exclusiveORExpression;
   public NodeOptional nodeOptional;

   public InclusiveORExpression(ExclusiveORExpression n0, NodeOptional n1) {
      exclusiveORExpression = n0;
      nodeOptional = n1;
   }

   public void accept(org.codecover.instrumentation.c.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(org.codecover.instrumentation.c.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(org.codecover.instrumentation.c.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(org.codecover.instrumentation.c.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

