//
// Generated by JTB 1.3.2
//

package org.codecover.instrumentation.c.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> "*"
 * nodeOptional -> [ TypeQualifierList() ]
 * nodeOptional1 -> [ Pointer() ]
 * </PRE>
 */
public class Pointer extends org.codecover.instrumentation.c.adapter.CCNode implements Node {
   public NodeToken nodeToken;
   public NodeOptional nodeOptional;
   public NodeOptional nodeOptional1;

   public Pointer(NodeToken n0, NodeOptional n1, NodeOptional n2) {
      nodeToken = n0;
      nodeOptional = n1;
      nodeOptional1 = n2;
   }

   public Pointer(NodeOptional n0, NodeOptional n1) {
      nodeToken = new NodeToken("*");
      nodeOptional = n0;
      nodeOptional1 = n1;
   }

   public void accept(org.codecover.instrumentation.c.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(org.codecover.instrumentation.c.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(org.codecover.instrumentation.c.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(org.codecover.instrumentation.c.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

